from .deapgeneric import DEAPGeneric
from .g3pcx import G3PCX
from .chc import CHC
from .nsgaii import NSGAII
from .nsgaiii import NSGAIII
from .moead import MOEAD
from .spea2 import SPEA2
from .peanltydeapgeneric import PenaltyDEAPGeneric
from .aldeapgeneric import ALDEAPGeneric